SELECT [LoanID]
       ,[Amount]
      ,[Loan Months Terms]
      ,[Start Date]
      ,[End Date]
      ,[Interest Rate] loan_type
      ,[Interest Rate]
      ,[Customer ID]
      ,[Branch ID]
  FROM [Union_Bank_OLTP].[dbo].[Loan]